In [ ]:
# Install Packages
!pip install kaggle --upgrade --quiet
!pip install opendatasets --upgrade --quiet
!pip install librosa --upgrade --quiet
!pip install noisereduce --upgrade --quiet

In [ ]:
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import os
import opendatasets as od
import csv

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
import seaborn as sns
import noisereduce as nr
from IPython.display import Audio
import librosa
import librosa.display
import wave

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

import prjLib as lib
import VictorLib as vic

import warnings
warnings.filterwarnings ('ignore')

In [ ]:
# Parameters

FRAME_LEN = 2048 # 4096
HOP_LEN = 512 # 2048
N = 128

FIGX = 14
FIGY = 2

In [ ]:
# Test Logistic Regression
oLR = LogisticRegression(random_state=0)
oLR.fit(speech_data_features, speech_label_array)
oLR.coef_.shape
plt.figure(figsize=(14, 6))
plt.plot(oLR.coef_[0,:],label='neutral')
plt.plot(oLR.coef_[1,:],label='calm')
plt.plot(oLR.coef_[2,:],label='happy')
plt.plot(oLR.coef_[3,:],label='sad')
plt.plot(oLR.coef_[4,:],label='angry')
plt.plot(oLR.coef_[5,:],label='fearful')
plt.plot(oLR.coef_[6,:],label='disgust')
plt.plot(oLR.coef_[7,:],label='surprised')
plt.legend()
plt.show()

In [1]:
!nvidia-smi --list-gpus
!conda create -n ml python=3.9
# !conda activate ml
# !conda install -c anaconda cudatoolkit
!conda install -c pytorch pytorch

GPU 0: NVIDIA GeForce RTX 4060 Ti (UUID: GPU-9a58fd84-6033-0736-2543-7c922e05178a)


In [2]:
import torch

torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [ ]:
device = torch.device('cuda') # 'cpu'

In [5]:
import time

matrix_size = 32*512
x = torch.randn(matrix_size,matrix_size)
y = torch.randn(matrix_size,matrix_size)
'''
print('CPU speed')
start = time.time()
result = torch.matmul(x,y)
print(time.time()-start)
print('Verify device: ',result.device)
'''

x_gpu = x.to(torch.device('cuda'))
y_gpu = y.to(torch.device('cuda'))
torch.cuda.synchronize()
for ii in range(3):
    print('GPU speed')
    start = time.time()
    result_gpu = x_gpu @ y_gpu # torch.matmul(x_gpu,y_gpu)
    torch.cuda.synchronize()
    print(time.time()-start)
    print('Verify device: ',result_gpu.device)


GPU speed
0.682175874710083
Verify device:  cuda:0
GPU speed
0.656245231628418
Verify device:  cuda:0
GPU speed
0.6522750854492188
Verify device:  cuda:0


In [28]:
a = torch.zeros([1,3],device=torch.device('cuda'))
a

tensor([[0., 0., 0.]], device='cuda:0')

In [23]:
b = torch.from_numpy(np.array([1,2]))
b

tensor([1, 2], dtype=torch.int32)

In [29]:
c = 2*a
c

tensor([[0., 0., 0.]], device='cuda:0')

In [ ]:
!conda install numba
!conda install cudatoolkit

In [4]:
from numba import jit, cuda 
import numpy as np 
# to measure exec time 
from timeit import default_timer as timer 

# normal function to run on cpu 
def func(a):								 
	for i in range(10000000): 
		a[i]+= 1	

# function optimized to run on gpu 
@jit(target_backend='cuda')						 
def func2(a): 
	for i in range(10000000): 
		a[i]+= 1
if __name__=="__main__": 
	n = 10000000							
	a = np.ones(n, dtype = np.float64) 
	
	start = timer() 
	func(a) 
	print("without GPU:", timer()-start)	 
	
	start = timer() 
	func2(a) 
	print("with GPU:", timer()-start) 


without GPU: 3.8525635870028054
with GPU: 0.8630010680062696
